name: snkeakyentitytweaks
version: "1.0"
main: com.danidipp.sneakyentitytweaks.SneakyEntityTweaks
api-version: "1.20"
authors:
  - DaniDipp
description: "Adjustments for entity default behaviors in a roleplay environment"
